import { split_data } from "@/Helpers/split_data";
import { StpData } from "@/Types/StpInterfaces";

type SplitReturn = ReturnType<typeof split_data<StpData>>
export async function getDataList(limit?: number, cursor?: number): Promise<SplitReturn> {
    if (!limit) return { sliced: datalist, prevCursor: 0, nextCursor: -1 }
    return split_data<StpData>(datalist, limit, cursor)
}
const datalist: StpData[] = [
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-16Ar-4",
        "tags": [
            "energy",
            "standart"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 52,
        "Ea": 20,
        "Er": 28,
        "Lr": 13,
        "Lt": 78,
        "Ro": 0.9,
        "Rw": 30,
        "S": 1.3,
        "Sf": 60,
        "weight": 20,
        "id": 1
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-16TGIAr-4FHbr",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 93,
        "Det": 29,
        "Ea": 47,
        "Er": 24,
        "Lr": 18,
        "Lt": 41,
        "Ro": 0.9,
        "Rw": 30,
        "S": 1.14,
        "Sf": 36,
        "weight": 20,
        "id": 2
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-16TGIAr-4FHgr",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 27,
        "Ea": 52,
        "Er": 21,
        "Lr": 15,
        "Lt": 37,
        "Ro": 0.9,
        "Rw": 30,
        "S": 1.09,
        "Sf": 34,
        "weight": 20,
        "id": 3
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-16Ar-4FHgr",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 27,
        "Ea": 52,
        "Er": 21,
        "Lr": 15,
        "Lt": 37,
        "Ro": 0.9,
        "Rw": 30,
        "S": 1.09,
        "Sf": 34,
        "weight": 20,
        "id": 4
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-16Ar-4FHbr",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 93,
        "Det": 29,
        "Ea": 47,
        "Er": 24,
        "Lr": 18,
        "Lt": 41,
        "Ro": 0.9,
        "Rw": 30,
        "S": 1.14,
        "Sf": 36,
        "weight": 20,
        "id": 5
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "3.3.1-14Ar-4Эл",
        "tags": [
            "hitproof",
            "multi",
            "solarproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 97,
        "Det": 37,
        "Ea": 22,
        "Er": 41,
        "Lr": 26,
        "Lt": 64,
        "Ro": 0.9,
        "Rw": 35,
        "S": 1.52,
        "Sf": 42,
        "weight": 25,
        "id": 6
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "6-14Ar-4Эл",
        "tags": [
            "multi",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 35,
        "Ea": 20,
        "Er": 41,
        "Lr": 26,
        "Lt": 64,
        "Ro": 0.9,
        "Rw": 36,
        "S": 1.52,
        "Sf": 42,
        "weight": 25,
        "id": 7
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4-16Ar-4Эл",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 40,
        "Ea": 19,
        "Er": 41,
        "Lr": 26,
        "Lt": 65,
        "Ro": 1,
        "Rw": 30,
        "S": 1.55,
        "Sf": 42,
        "weight": 20,
        "id": 8
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-14Ar-6FHcl",
        "tags": [
            "energy",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 41,
        "Ea": 21,
        "Er": 38,
        "Lr": 33,
        "Lt": 59,
        "Ro": 0.9,
        "Rw": 36,
        "S": 1.23,
        "Sf": 48,
        "weight": 25,
        "id": 9
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-16Ar-4FHcl",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 42,
        "Ea": 17,
        "Er": 41,
        "Lr": 34,
        "Lt": 60,
        "Ro": 0.9,
        "Rw": 30,
        "S": 1.22,
        "Sf": 49,
        "weight": 20,
        "id": 10
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "6TopN-10Ar-4.4.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 96,
        "Det": 45,
        "Ea": 33,
        "Er": 20,
        "Lr": 12,
        "Lt": 76,
        "Ro": 0.7,
        "Rw": 35,
        "S": 1.41,
        "Sf": 53,
        "weight": 35,
        "id": 11
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-12Ar-4.4.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 96,
        "Det": 47,
        "Ea": 32,
        "Er": 21,
        "Lr": 12,
        "Lt": 77,
        "Ro": 0.8,
        "Rw": 36,
        "S": 1.43,
        "Sf": 54,
        "weight": 30,
        "id": 12
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-14Ar-3.3.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 97,
        "Det": 48,
        "Ea": 30,
        "Er": 28,
        "Lr": 13,
        "Lt": 78,
        "Ro": 0.7,
        "Rw": 35,
        "S": 1.39,
        "Sf": 55,
        "weight": 25,
        "id": 13
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4-16Ar-4Сбр",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 93,
        "Det": 29,
        "Ea": 47,
        "Er": 24,
        "Lr": 18,
        "Lt": 41,
        "Ro": 0.9,
        "Rw": 30,
        "S": 1.14,
        "Sf": 36,
        "weight": 20,
        "id": 14
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-16-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 53,
        "Ea": 20,
        "Er": 28,
        "Lr": 13,
        "Lt": 79,
        "Ro": 0.7,
        "Rw": 30,
        "S": 1.42,
        "Sf": 55,
        "weight": 20,
        "id": 15
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4-12-4.4.1",
        "tags": [
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 97,
        "Det": 62,
        "Ea": 27,
        "Er": 11,
        "Lr": 14,
        "Lt": 79,
        "Ro": 0.4,
        "Rw": 36,
        "S": 1.18,
        "Sf": 67,
        "weight": 30,
        "id": 16
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "6-10-4.4.1",
        "tags": [
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 96,
        "Det": 59,
        "Ea": 30,
        "Er": 11,
        "Lr": 14,
        "Lt": 78,
        "Ro": 0.3,
        "Rw": 35,
        "S": 1.16,
        "Sf": 67,
        "weight": 35,
        "id": 17
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4-14-3.3.1",
        "tags": [
            "hitproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 97,
        "Det": 64,
        "Ea": 24,
        "Er": 12,
        "Lr": 14,
        "Lt": 80,
        "Ro": 0.3,
        "Rw": 36,
        "S": 1.16,
        "Sf": 69,
        "weight": 25,
        "id": 18
    },
    {
        "cams": 2,
        "depth": 24,
        "name": "4-6-4-6-4",
        "tags": [
            "simple"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 68,
        "Ea": 14,
        "Er": 18,
        "Lr": 20,
        "Lt": 75,
        "Ro": 0.4,
        "Rw": 33,
        "S": 1.04,
        "Sf": 72,
        "weight": 30,
        "id": 19
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4-14-6",
        "tags": [
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 99,
        "Det": 74,
        "Ea": 18,
        "Er": 13,
        "Lr": 15,
        "Lt": 81,
        "Ro": 0.4,
        "Rw": 36,
        "S": 1.04,
        "Sf": 78,
        "weight": 25,
        "id": 20
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4-16-4",
        "tags": [
            "standart"
        ],
        "secure": "нет",
        "Ra": 99,
        "Det": 76,
        "Ea": 10,
        "Er": 14,
        "Lr": 15,
        "Lt": 82,
        "Ro": 0.4,
        "Rw": 30,
        "S": 1.03,
        "Sf": 80,
        "weight": 20,
        "id": 21
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "6-14Ar-4TopN",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 39,
        "Ea": 20,
        "Er": 41,
        "Lr": 26,
        "Lt": 64,
        "Ro": 0.9,
        "Rw": 36,
        "S": 1.52,
        "Sf": 42,
        "weight": 25,
        "id": 22
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-14TGIAr-3.3.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 97,
        "Det": 48,
        "Ea": 30,
        "Er": 28,
        "Lr": 13,
        "Lt": 78,
        "Ro": 0.7,
        "Rw": 35,
        "S": 1.39,
        "Sf": 55,
        "weight": 25,
        "id": 23
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-16TGIAr-4FHcl",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 42,
        "Ea": 17,
        "Er": 41,
        "Lr": 34,
        "Lt": 60,
        "Ro": 0.9,
        "Rw": 30,
        "S": 1.22,
        "Sf": 49,
        "weight": 20,
        "id": 24
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-16TGIAr-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 52,
        "Ea": 20,
        "Er": 28,
        "Lr": 13,
        "Lt": 78,
        "Ro": 0.9,
        "Rw": 30,
        "S": 1.3,
        "Sf": 60,
        "weight": 20,
        "id": 25
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "6TopN-14Ar-4",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 50,
        "Ea": 22,
        "Er": 28,
        "Lr": 13,
        "Lt": 77,
        "Ro": 0.9,
        "Rw": 36,
        "S": 1.28,
        "Sf": 60,
        "weight": 25,
        "id": 26
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4TopN-14Ar-6",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 50,
        "Ea": 25,
        "Er": 25,
        "Lr": 13,
        "Lt": 77,
        "Ro": 0.9,
        "Rw": 36,
        "S": 1.31,
        "Sf": 59,
        "weight": 25,
        "id": 27
    },
    {
        "cams": 1,
        "depth": 24,
        "name": "4-16-4Эл",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 40,
        "Ea": 19,
        "Er": 41,
        "Lr": 26,
        "Lt": 65,
        "Ro": 0.77,
        "Rw": 30,
        "S": 1.51,
        "Sf": 43,
        "weight": 20,
        "id": 28
    },
    {
        "cams": 1,
        "depth": 28,
        "name": "4TopN-20Ar-4FHbr",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 93,
        "Det": 29,
        "Ea": 47,
        "Er": 24,
        "Lr": 18,
        "Lt": 41,
        "Ro": 0.9,
        "Rw": 31,
        "S": 1.14,
        "Sf": 36,
        "weight": 20,
        "id": 29
    },
    {
        "cams": 1,
        "depth": 28,
        "name": "4TopN-20Ar-4FHgr",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 27,
        "Ea": 52,
        "Er": 21,
        "Lr": 15,
        "Lt": 37,
        "Ro": 0.9,
        "Rw": 31,
        "S": 1.09,
        "Sf": 34,
        "weight": 20,
        "id": 30
    },
    {
        "cams": 1,
        "depth": 28,
        "name": "4-20Ar-4Эл",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 40,
        "Ea": 19,
        "Er": 40,
        "Lr": 26,
        "Lt": 65,
        "Ro": 0.9,
        "Rw": 31,
        "S": 1.51,
        "Sf": 43,
        "weight": 20,
        "id": 31
    },
    {
        "cams": 1,
        "depth": 28,
        "name": "4TopN-20Ar-4FHcl",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 42,
        "Ea": 17,
        "Er": 41,
        "Lr": 34,
        "Lt": 60,
        "Ro": 0.9,
        "Rw": 31,
        "S": 1.22,
        "Sf": 49,
        "weight": 20,
        "id": 32
    },
    {
        "cams": 1,
        "depth": 28,
        "name": "4-20Ar-4Сбр",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 93,
        "Det": 29,
        "Ea": 47,
        "Er": 24,
        "Lr": 18,
        "Lt": 41,
        "Ro": 0.9,
        "Rw": 31,
        "S": 1.14,
        "Sf": 36,
        "weight": 20,
        "id": 33
    },
    {
        "cams": 1,
        "depth": 28,
        "name": "4TopN-20-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 53,
        "Ea": 20,
        "Er": 28,
        "Lr": 13,
        "Lt": 79,
        "Ro": 0.7,
        "Rw": 31,
        "S": 1.39,
        "Sf": 56,
        "weight": 20,
        "id": 34
    },
    {
        "cams": 1,
        "depth": 28,
        "name": "4-20-4",
        "tags": [
            "standart"
        ],
        "secure": "нет",
        "Ra": 99,
        "Det": 76,
        "Ea": 10,
        "Er": 14,
        "Lr": 15,
        "Lt": 82,
        "Ro": 0.4,
        "Rw": 31,
        "S": 1.03,
        "Sf": 80,
        "weight": 20,
        "id": 35
    },
    {
        "cams": 1,
        "depth": 28,
        "name": "4TopN-20Ar-4",
        "tags": [
            "energy",
            "standart"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 52,
        "Ea": 20,
        "Er": 28,
        "Lr": 13,
        "Lt": 78,
        "Ro": 0.9,
        "Rw": 31,
        "S": 1.3,
        "Sf": 60,
        "weight": 20,
        "id": 36
    },
    {
        "cams": 1,
        "depth": 28,
        "name": "4-20-4Эл",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 40,
        "Ea": 19,
        "Er": 41,
        "Lr": 26,
        "Lt": 65,
        "Ro": 0.8,
        "Rw": 31,
        "S": 1.51,
        "Sf": 43,
        "weight": 20,
        "id": 37
    },
    {
        "cams": 1,
        "depth": 28,
        "name": "4TopN-20TGIAr-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 52,
        "Ea": 20,
        "Er": 28,
        "Lr": 13,
        "Lt": 78,
        "Ro": 0.9,
        "Rw": 31,
        "S": 1.3,
        "Sf": 60,
        "weight": 20,
        "id": 38
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4TopN-10-4-10-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 28,
        "Lr": 18,
        "Lt": 71,
        "Ro": 0.71,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 39
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4-10-4-10-4Эл",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 35,
        "Ea": 22,
        "Er": 43,
        "Lr": 30,
        "Lt": 59,
        "Ro": 0.71,
        "Rw": 33,
        "S": 1.48,
        "Sf": 40,
        "weight": 30,
        "id": 40
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4-10-4-10Ar-4Сбр",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 94,
        "Det": 37,
        "Ea": 46,
        "Er": 17,
        "Lr": 20,
        "Lt": 39,
        "Ro": 0.9,
        "Rw": 33,
        "S": 1.35,
        "Sf": 44,
        "weight": 30,
        "id": 41
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4-10-4-10Ar-4Эл",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 35,
        "Ea": 22,
        "Er": 36,
        "Lr": 30,
        "Lt": 59,
        "Ro": 0.9,
        "Rw": 33,
        "S": 1.48,
        "Sf": 40,
        "weight": 30,
        "id": 42
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4TopN-8Ar-4TopN-12Ar-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 39,
        "Ea": 29,
        "Er": 32,
        "Lr": 17,
        "Lt": 69,
        "Ro": 1.25,
        "Rw": 33,
        "S": 1.35,
        "Sf": 51,
        "weight": 30,
        "id": 43
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4TopN-10Ar-4TopN-10Ar-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 39,
        "Ea": 29,
        "Er": 32,
        "Lr": 17,
        "Lt": 69,
        "Ro": 1.25,
        "Rw": 33,
        "S": 1.38,
        "Sf": 50,
        "weight": 30,
        "id": 44
    },
    {
        "cams": 1,
        "depth": 32,
        "name": "4TopN-22Ar-6",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 50,
        "Ea": 25,
        "Er": 25,
        "Lr": 13,
        "Lt": 77,
        "Ro": 0.83,
        "Rw": 36,
        "S": 1.31,
        "Sf": 59,
        "weight": 25,
        "id": 45
    },
    {
        "cams": 1,
        "depth": 32,
        "name": "4TopN-24Ar-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 52,
        "Ea": 20,
        "Er": 28,
        "Lr": 13,
        "Lt": 78,
        "Ro": 0.83,
        "Rw": 32,
        "S": 1.3,
        "Sf": 60,
        "weight": 20,
        "id": 46
    },
    {
        "cams": 1,
        "depth": 32,
        "name": "6TopN-22Ar-4",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 50,
        "Ea": 22,
        "Er": 28,
        "Lr": 13,
        "Lt": 77,
        "Ro": 0.83,
        "Rw": 36,
        "S": 1.28,
        "Sf": 60,
        "weight": 25,
        "id": 47
    },
    {
        "cams": 1,
        "depth": 32,
        "name": "4-24-4",
        "tags": [
            "simple"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 72,
        "Ea": 15,
        "Er": 13,
        "Lr": 15,
        "Lt": 81,
        "Ro": 0.36,
        "Rw": 32,
        "S": 1.05,
        "Sf": 77,
        "weight": 20,
        "id": 48
    },
    {
        "cams": 1,
        "depth": 32,
        "name": "4-22-6",
        "tags": [
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 70,
        "Ea": 18,
        "Er": 12,
        "Lr": 14,
        "Lt": 80,
        "Ro": 0.37,
        "Rw": 36,
        "S": 1.07,
        "Sf": 75,
        "weight": 25,
        "id": 49
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "6TopN-9Ar-4-9-4",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 44,
        "Ea": 29,
        "Er": 27,
        "Lr": 18,
        "Lt": 70,
        "Ro": 0.83,
        "Rw": 36,
        "S": 1.27,
        "Sf": 55,
        "weight": 35,
        "id": 50
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4TopN-9Ar-4-9-6",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 44,
        "Ea": 31,
        "Er": 25,
        "Lr": 18,
        "Lt": 70,
        "Ro": 0.83,
        "Rw": 36,
        "S": 1.32,
        "Sf": 53,
        "weight": 35,
        "id": 51
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4-9-4-9-6",
        "tags": [
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 60,
        "Ea": 24,
        "Er": 16,
        "Lr": 20,
        "Lt": 73,
        "Ro": 0.5,
        "Rw": 36,
        "S": 1.09,
        "Sf": 67,
        "weight": 35,
        "id": 52
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4TopN-8Ar-4-12-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 31,
        "Lr": 18,
        "Lt": 71,
        "Ro": 0.8,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 53
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4TopN-10Ar-4-10-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 31,
        "Lr": 18,
        "Lt": 71,
        "Ro": 0.83,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 54
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4-8-4-12-4",
        "tags": [
            "simple"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 62,
        "Ea": 21,
        "Er": 17,
        "Lr": 20,
        "Lt": 74,
        "Ro": 0.5,
        "Rw": 33,
        "S": 1.07,
        "Sf": 70,
        "weight": 30,
        "id": 55
    },
    {
        "cams": 2,
        "depth": 32,
        "name": "4-10-4-10-4",
        "tags": [
            "simple"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 62,
        "Ea": 21,
        "Er": 17,
        "Lr": 20,
        "Lt": 74,
        "Ro": 0.5,
        "Rw": 33,
        "S": 1.06,
        "Sf": 70,
        "weight": 30,
        "id": 56
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-12Ar-4-12-4FHbr",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 94,
        "Det": 26,
        "Ea": 51,
        "Er": 23,
        "Lr": 20,
        "Lt": 38,
        "Ro": 1,
        "Rw": 33,
        "S": 1.15,
        "Sf": 33,
        "weight": 30,
        "id": 57
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-12Ar-4-12-4FHgr",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 24,
        "Ea": 56,
        "Er": 20,
        "Lr": 17,
        "Lt": 34,
        "Ro": 1,
        "Rw": 33,
        "S": 1.1,
        "Sf": 31,
        "weight": 30,
        "id": 58
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-12TGI-4-12TGI-4FHbr",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 94,
        "Det": 26,
        "Ea": 51,
        "Er": 23,
        "Lr": 20,
        "Lt": 38,
        "Ro": 0.77,
        "Rw": 33,
        "S": 1.12,
        "Sf": 34,
        "weight": 30,
        "id": 59
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-12TGI-4-12TGI-4FHgr",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 24,
        "Ea": 56,
        "Er": 38,
        "Lr": 17,
        "Lt": 34,
        "Ro": 0.77,
        "Rw": 33,
        "S": 1.1,
        "Sf": 31,
        "weight": 30,
        "id": 60
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-12Ar-4-12-4FHcl",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 37,
        "Ea": 24,
        "Er": 39,
        "Lr": 37,
        "Lt": 55,
        "Ro": 1,
        "Rw": 33,
        "S": 1.21,
        "Sf": 45,
        "weight": 30,
        "id": 61
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "6TopN-9Ar-4-9-4.4.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 95,
        "Det": 40,
        "Ea": 39,
        "Er": 28,
        "Lr": 18,
        "Lt": 69,
        "Ro": 0.83,
        "Rw": 39,
        "S": 1.41,
        "Sf": 49,
        "weight": 45,
        "id": 62
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-10Ar-4-10-4.4.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 95,
        "Det": 41,
        "Ea": 38,
        "Er": 21,
        "Lr": 18,
        "Lt": 70,
        "Ro": 0.8,
        "Rw": 37,
        "S": 1.43,
        "Sf": 49,
        "weight": 40,
        "id": 63
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-10Ar-4-12-3.3.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 96,
        "Det": 42,
        "Ea": 36,
        "Er": 22,
        "Lr": 18,
        "Lt": 70,
        "Ro": 0.9,
        "Rw": 36,
        "S": 1.4,
        "Sf": 51,
        "weight": 37,
        "id": 64
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-12Ar-4TopN-12Ar-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 40,
        "Ea": 29,
        "Er": 33,
        "Lr": 18,
        "Lt": 69,
        "Ro": 1.4,
        "Rw": 33,
        "S": 1.35,
        "Sf": 50,
        "weight": 30,
        "id": 65
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4-12-4-12Ar-4Сбр",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 94,
        "Det": 37,
        "Ea": 46,
        "Er": 17,
        "Lr": 20,
        "Lt": 39,
        "Ro": 1,
        "Rw": 33,
        "S": 1.3,
        "Sf": 44,
        "weight": 30,
        "id": 66
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "6-9-4-9-4.4.1",
        "tags": [
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 95,
        "Det": 52,
        "Ea": 34,
        "Er": 16,
        "Lr": 19,
        "Lt": 71,
        "Ro": 0.5,
        "Rw": 39,
        "S": 1.18,
        "Sf": 60,
        "weight": 45,
        "id": 67
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4-10-4-10-4.4.1",
        "tags": [
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 96,
        "Det": 53,
        "Ea": 31,
        "Er": 14,
        "Lr": 19,
        "Lt": 72,
        "Ro": 0.5,
        "Rw": 37,
        "S": 1.2,
        "Sf": 60,
        "weight": 40,
        "id": 68
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4-10-4-12-3.3.1",
        "tags": [
            "hitproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 96,
        "Det": 55,
        "Ea": 30,
        "Er": 15,
        "Lr": 20,
        "Lt": 73,
        "Ro": 0.5,
        "Rw": 36,
        "S": 1.18,
        "Sf": 62,
        "weight": 35,
        "id": 69
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-12-4-12-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 28,
        "Lr": 18,
        "Lt": 71,
        "Ro": 0.77,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 70
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4-12-4-12-4Эл",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 35,
        "Ea": 22,
        "Er": 43,
        "Lr": 30,
        "Lt": 59,
        "Ro": 0.83,
        "Rw": 33,
        "S": 1.48,
        "Sf": 40,
        "weight": 30,
        "id": 71
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "6-10-4-12-4Эл",
        "tags": [
            "multi",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 34,
        "Ea": 23,
        "Er": 43,
        "Lr": 30,
        "Lt": 59,
        "Ro": 0.83,
        "Rw": 36,
        "S": 1.48,
        "Sf": 40,
        "weight": 35,
        "id": 72
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "6-10-4-12Ar-4Эл",
        "tags": [
            "multi",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 34,
        "Ea": 23,
        "Er": 43,
        "Lr": 30,
        "Lt": 59,
        "Ro": 1,
        "Rw": 36,
        "S": 1.48,
        "Sf": 40,
        "weight": 35,
        "id": 73
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "3.3.1-10-4-12Ar-4Эл",
        "tags": [
            "hitproof",
            "multi",
            "solarproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 96,
        "Det": 33,
        "Ea": 24,
        "Er": 43,
        "Lr": 30,
        "Lt": 59,
        "Ro": 1,
        "Rw": 36,
        "S": 1.51,
        "Sf": 39,
        "weight": 35,
        "id": 74
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-10TGIAr-4-12TGI-3.3.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 96,
        "Det": 42,
        "Ea": 35,
        "Er": 23,
        "Lr": 18,
        "Lt": 70,
        "Ro": 0.9,
        "Rw": 36,
        "S": 1.37,
        "Sf": 51,
        "weight": 35,
        "id": 75
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-12TGI-4-12TGI-4FHcl",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 37,
        "Ea": 24,
        "Er": 39,
        "Lr": 37,
        "Lt": 55,
        "Ro": 0.8,
        "Rw": 33,
        "S": 1.22,
        "Sf": 45,
        "weight": 30,
        "id": 76
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-10Ar-4-12-6FHcl",
        "tags": [
            "energy",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 36,
        "Ea": 27,
        "Er": 37,
        "Lr": 36,
        "Lt": 54,
        "Ro": 0.9,
        "Rw": 36,
        "S": 1.23,
        "Sf": 44,
        "weight": 35,
        "id": 77
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-10TGIAr-4-10TGI-4.4.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 95,
        "Det": 41,
        "Ea": 38,
        "Er": 21,
        "Lr": 18,
        "Lt": 70,
        "Ro": 0.83,
        "Rw": 37,
        "S": 1.43,
        "Sf": 49,
        "weight": 40,
        "id": 78
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-10TGI-4-10TGI-4.4.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 95,
        "Det": 41,
        "Ea": 38,
        "Er": 21,
        "Lr": 18,
        "Lt": 70,
        "Ro": 0.71,
        "Rw": 37,
        "S": 1.4,
        "Sf": 50,
        "weight": 40,
        "id": 79
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "6TopN-10TGIAr-4-12TGI-4",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 44,
        "Ea": 29,
        "Er": 27,
        "Lr": 18,
        "Lt": 70,
        "Ro": 0.9,
        "Rw": 36,
        "S": 1.27,
        "Sf": 55,
        "weight": 35,
        "id": 80
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-10TGIAr-4-14TGI-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 31,
        "Lr": 18,
        "Lt": 71,
        "Ro": 0.9,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 81
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-12TGIAr-4-12TGI-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 28,
        "Lr": 18,
        "Lt": 71,
        "Ro": 1,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 82
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-10TGIAr-4-12TGI-6",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 44,
        "Ea": 31,
        "Er": 25,
        "Lr": 18,
        "Lt": 70,
        "Ro": 0.9,
        "Rw": 36,
        "S": 1.3,
        "Sf": 54,
        "weight": 35,
        "id": 83
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "6TopN-10Ar-4-12-4",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 44,
        "Ea": 29,
        "Er": 27,
        "Lr": 18,
        "Lt": 70,
        "Ro": 0.9,
        "Rw": 36,
        "S": 1.27,
        "Sf": 55,
        "weight": 35,
        "id": 84
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4-10-4-12-6",
        "tags": [
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 60,
        "Ea": 24,
        "Er": 16,
        "Lr": 20,
        "Lt": 73,
        "Ro": 0.53,
        "Rw": 36,
        "S": 1.09,
        "Sf": 67,
        "weight": 35,
        "id": 85
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-10Ar-4-14-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 28,
        "Lr": 18,
        "Lt": 71,
        "Ro": 0.9,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 86
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4TopN-12Ar-4-12-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 28,
        "Lr": 18,
        "Lt": 71,
        "Ro": 1,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 87
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4-10-4-14-4",
        "tags": [
            "simple"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 62,
        "Ea": 21,
        "Er": 17,
        "Lr": 20,
        "Lt": 74,
        "Ro": 0.53,
        "Rw": 33,
        "S": 1.06,
        "Sf": 70,
        "weight": 30,
        "id": 88
    },
    {
        "cams": 2,
        "depth": 36,
        "name": "4-12-4-12-4",
        "tags": [
            "simple"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 62,
        "Ea": 21,
        "Er": 17,
        "Lr": 20,
        "Lt": 74,
        "Ro": 0.53,
        "Rw": 33,
        "S": 1.06,
        "Sf": 70,
        "weight": 30,
        "id": 89
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4TopN-12Ar-4-12-4.4.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 95,
        "Det": 41,
        "Ea": 38,
        "Er": 21,
        "Lr": 18,
        "Lt": 70,
        "Ro": 1,
        "Rw": 37,
        "S": 1.43,
        "Sf": 49,
        "weight": 40,
        "id": 90
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4TopN-12Ar-4-14-3.3.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 96,
        "Det": 42,
        "Ea": 36,
        "Er": 22,
        "Lr": 18,
        "Lt": 70,
        "Ro": 1,
        "Rw": 36,
        "S": 1.4,
        "Sf": 50,
        "weight": 35,
        "id": 91
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4TopN-14Ar-4TopN-14Ar-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 39,
        "Ea": 29,
        "Er": 33,
        "Lr": 18,
        "Lt": 69,
        "Ro": 1.7,
        "Rw": 33,
        "S": 1.35,
        "Sf": 50,
        "weight": 30,
        "id": 92
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4TopN-12Ar-4-14-6",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 44,
        "Ea": 31,
        "Er": 31,
        "Lr": 18,
        "Lt": 71,
        "Ro": 1,
        "Rw": 36,
        "S": 1.32,
        "Sf": 53,
        "weight": 35,
        "id": 93
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4TopN-14Ar-4-14-4",
        "tags": [
            "energy",
            "standart"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 46,
        "Ea": 26,
        "Er": 31,
        "Lr": 18,
        "Lt": 72,
        "Ro": 1.1,
        "Rw": 33,
        "S": 1.26,
        "Sf": 55,
        "weight": 30,
        "id": 94
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4-12-4-12-4.4.1",
        "tags": [
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 96,
        "Det": 53,
        "Ea": 31,
        "Er": 14,
        "Lr": 19,
        "Lt": 72,
        "Ro": 0.5,
        "Rw": 37,
        "S": 1.2,
        "Sf": 60,
        "weight": 40,
        "id": 95
    },
    {
        "cams": 2,
        "depth": 38,
        "name": "4-12-4-12-3.3.1",
        "tags": [
            "hitproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 96,
        "Det": 55,
        "Ea": 30,
        "Er": 15,
        "Lr": 20,
        "Lt": 73,
        "Ro": 0.5,
        "Rw": 36,
        "S": 1.18,
        "Sf": 62,
        "weight": 37,
        "id": 96
    },
    {
        "cams": 1,
        "depth": 40,
        "name": "4.4.1-24-4.4.1",
        "tags": [
            "hitproof",
            "soundproof"
        ],
        "secure": "CM3",
        "Ra": 96,
        "Det": 56,
        "Ea": 33,
        "Er": 11,
        "Lr": 14,
        "Lt": 78,
        "Ro": 0.4,
        "Rw": 41,
        "S": 1.18,
        "Sf": 66,
        "weight": 41,
        "id": 97
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4-14-4-14-4",
        "tags": [
            "standart"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 68,
        "Ea": 21,
        "Er": 18,
        "Lr": 20,
        "Lt": 75,
        "Ro": 0.6,
        "Rw": 33,
        "S": 1.03,
        "Sf": 73,
        "weight": 30,
        "id": 98
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4TopN-14Ar-4-14-4FHcl",
        "tags": [
            "energy",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 98,
        "Det": 37,
        "Ea": 24,
        "Er": 39,
        "Lr": 37,
        "Lt": 55,
        "Ro": 1.1,
        "Rw": 33,
        "S": 1.22,
        "Sf": 45,
        "weight": 30,
        "id": 99
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4TopN-14-4-14-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 28,
        "Lr": 18,
        "Lt": 71,
        "Ro": 0.9,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 100
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4-14-4-14-4Эл",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 35,
        "Ea": 22,
        "Er": 43,
        "Lr": 30,
        "Lt": 59,
        "Ro": 1,
        "Rw": 33,
        "S": 1.48,
        "Sf": 40,
        "weight": 30,
        "id": 101
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4-14-4-14Аr-4Сбр",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 94,
        "Det": 37,
        "Ea": 46,
        "Er": 17,
        "Lr": 20,
        "Lt": 39,
        "Ro": 1.25,
        "Rw": 33,
        "S": 1.3,
        "Sf": 44,
        "weight": 30,
        "id": 102
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4TopN-14ArС-4-14С-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 28,
        "Lr": 18,
        "Lt": 71,
        "Ro": 0.9,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 103
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4TopN-14ArЧ-4-14Ч-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 28,
        "Lr": 18,
        "Lt": 71,
        "Ro": 0.9,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 104
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4-12-4-16Ar-4Эл",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 35,
        "Ea": 22,
        "Er": 43,
        "Lr": 30,
        "Lt": 59,
        "Ro": 1.25,
        "Rw": 33,
        "S": 1.48,
        "Sf": 40,
        "weight": 30,
        "id": 105
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4TopN-12Ar-4-16-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 28,
        "Lr": 18,
        "Lt": 71,
        "Ro": 1,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 106
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4-14TGI-4-14TGIAr-4Эл",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 35,
        "Ea": 22,
        "Er": 43,
        "Lr": 30,
        "Lt": 59,
        "Ro": 1.11,
        "Rw": 33,
        "S": 1.48,
        "Sf": 40,
        "weight": 30,
        "id": 107
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4-14-4-14Ar-4Эл",
        "tags": [
            "multi",
            "solarproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 35,
        "Ea": 22,
        "Er": 43,
        "Lr": 30,
        "Lt": 59,
        "Ro": 1.11,
        "Rw": 33,
        "S": 1.48,
        "Sf": 40,
        "weight": 30,
        "id": 108
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4-12-4-14-6",
        "tags": [
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 60,
        "Ea": 24,
        "Er": 16,
        "Lr": 20,
        "Lt": 73,
        "Ro": 0.53,
        "Rw": 36,
        "S": 1.09,
        "Sf": 67,
        "weight": 35,
        "id": 109
    },
    {
        "cams": 2,
        "depth": 40,
        "name": "4-12TGI-4-14TGI-6",
        "tags": [
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 60,
        "Ea": 24,
        "Er": 16,
        "Lr": 20,
        "Lt": 73,
        "Ro": 0.53,
        "Rw": 36,
        "S": 1.09,
        "Sf": 67,
        "weight": 35,
        "id": 110
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopN-18Ar-4-18-6",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 95,
        "Det": 43,
        "Ea": 32,
        "Er": 25,
        "Lr": 18,
        "Lt": 69,
        "Ro": 1.11,
        "Rw": 36,
        "S": 1.3,
        "Sf": 53,
        "weight": 40,
        "id": 111
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopN-18Ar-4TopN-18Ar-6",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 95,
        "Det": 37,
        "Ea": 34,
        "Er": 29,
        "Lr": 16,
        "Lt": 67,
        "Ro": 2,
        "Rw": 36,
        "S": 1.37,
        "Sf": 49,
        "weight": 40,
        "id": 112
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopN-18Ar-4-18-3.3.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 95,
        "Det": 41,
        "Ea": 36,
        "Er": 23,
        "Lr": 18,
        "Lt": 70,
        "Ro": 1.11,
        "Rw": 37,
        "S": 1.4,
        "Sf": 50,
        "weight": 40,
        "id": 113
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopN-18Ar-4-18-6FHcl",
        "tags": [
            "energy",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 35,
        "Ea": 28,
        "Er": 37,
        "Lr": 36,
        "Lt": 54,
        "Ro": 1.11,
        "Rw": 36,
        "S": 1.23,
        "Sf": 44,
        "weight": 40,
        "id": 114
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6-18-4-18Ar-6Эл",
        "tags": [
            "multi",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 34,
        "Ea": 25,
        "Er": 41,
        "Lr": 29,
        "Lt": 58,
        "Ro": 1.25,
        "Rw": 36,
        "S": 1.49,
        "Sf": 39,
        "weight": 40,
        "id": 115
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6-18Ar-4TopN-18Ar-6Эл",
        "tags": [
            "energy",
            "multi",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 95,
        "Det": 30,
        "Ea": 29,
        "Er": 41,
        "Lr": 29,
        "Lt": 56,
        "Ro": 2,
        "Rw": 36,
        "S": 1.56,
        "Sf": 36,
        "weight": 40,
        "id": 116
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopN-18TGIAr-4-18TGI-6",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 95,
        "Det": 43,
        "Ea": 32,
        "Er": 25,
        "Lr": 18,
        "Lt": 69,
        "Ro": 1.11,
        "Rw": 36,
        "S": 1.3,
        "Sf": 53,
        "weight": 40,
        "id": 117
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopN-18TGIAr-4TopN-18TGIAr-6",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 95,
        "Det": 37,
        "Ea": 34,
        "Er": 29,
        "Lr": 16,
        "Lt": 67,
        "Ro": 2,
        "Rw": 36,
        "S": 1.37,
        "Sf": 49,
        "weight": 40,
        "id": 118
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopN-18TGIAr-4-18TGI-3.3.1",
        "tags": [
            "energy",
            "hitproof",
            "soundproof"
        ],
        "secure": "CM2",
        "Ra": 95,
        "Det": 41,
        "Ea": 36,
        "Er": 23,
        "Lr": 18,
        "Lt": 70,
        "Ro": 1.11,
        "Rw": 37,
        "S": 1.4,
        "Sf": 50,
        "weight": 40,
        "id": 119
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopN-18TGIAr-4-18TGI-6FHcl",
        "tags": [
            "energy",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 97,
        "Det": 35,
        "Ea": 28,
        "Er": 37,
        "Lr": 36,
        "Lt": 54,
        "Ro": 1,
        "Rw": 36,
        "S": 1.23,
        "Sf": 44,
        "weight": 40,
        "id": 120
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6-18TGI-4-18TGIAr-6Эл",
        "tags": [
            "multi",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 34,
        "Ea": 25,
        "Er": 41,
        "Lr": 29,
        "Lt": 58,
        "Ro": 1.25,
        "Rw": 36,
        "S": 1.49,
        "Sf": 39,
        "weight": 40,
        "id": 121
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6-18TGIAr-4TopN-18TGIAr-6Эл",
        "tags": [
            "energy",
            "multi",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 95,
        "Det": 30,
        "Ea": 29,
        "Er": 41,
        "Lr": 29,
        "Lt": 56,
        "Ro": 2,
        "Rw": 36,
        "S": 1.56,
        "Sf": 36,
        "weight": 40,
        "id": 122
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopN-16ЧAr-4-20Ч-6",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 95,
        "Det": 43,
        "Ea": 32,
        "Er": 25,
        "Lr": 18,
        "Lt": 69,
        "Ro": 1.11,
        "Rw": 36,
        "S": 1.3,
        "Sf": 53,
        "weight": 40,
        "id": 123
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopN-16СAr-4-20С-6",
        "tags": [
            "energy",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 95,
        "Det": 43,
        "Ea": 32,
        "Er": 25,
        "Lr": 18,
        "Lt": 69,
        "Ro": 1.11,
        "Rw": 36,
        "S": 1.3,
        "Sf": 53,
        "weight": 40,
        "id": 124
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6-18-6-18Ar-4Сбр",
        "tags": [
            "multi",
            "solarproof",
            "soundproof"
        ],
        "secure": "нет",
        "Ra": 95,
        "Det": 34,
        "Ea": 49,
        "Er": 17,
        "Lr": 20,
        "Lt": 38,
        "Ro": 1.25,
        "Rw": 36,
        "S": 1.35,
        "Sf": 43,
        "weight": 40,
        "id": 125
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopN-16Ar-6-18-6",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 95,
        "Det": 42,
        "Ea": 34,
        "Er": 24,
        "Lr": 18,
        "Lt": 69,
        "Ro": 1.11,
        "Rw": 35,
        "S": 1.33,
        "Sf": 52,
        "weight": 45,
        "id": 126
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "6TopNзак-16Ar-6зак-18-6зак",
        "tags": [
            "hitproof"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 45,
        "Ea": 33,
        "Er": 22,
        "Lr": 18,
        "Lt": 70,
        "Ro": 1.11,
        "Rw": 35,
        "S": 1.27,
        "Sf": 55,
        "weight": 45,
        "id": 127
    },
    {
        "cams": 2,
        "depth": 52,
        "name": "4TopN-20Ar-4-20-4",
        "tags": [
            "energy"
        ],
        "secure": "нет",
        "Ra": 96,
        "Det": 46,
        "Ea": 26,
        "Er": 28,
        "Lr": 18,
        "Lt": 71,
        "Ro": 1.11,
        "Rw": 33,
        "S": 1.29,
        "Sf": 55,
        "weight": 30,
        "id": 128
    }
]

export default datalist